name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch (Dockerfile)
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Checkout master branch (task assignment files)
      run: git checkout master

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build Docker image
      run: docker build . -t ghcr.io/${{ github.repository_owner }}/task-assignment-api:latest

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/task-assignment-api:latest
